[project]
name = "tdd-1"
version = "0.1.0"
description = "Playing with TDD in python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.5",
    "httpx>=0.28.0",
    "pytest>=8.3.3",
    "uvicorn>=0.32.1",
]
